# Generated by Django 4.2.4 on 2023-10-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_data_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_data',
        ),
    ]
